# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f17a19be60b993064b703e3ac476db7f1128b8656f2ebeed973fb9151fc1ba5dddfda2bca42ec27710345aa5e6eb286385b5ec4febffcebf2c750674e4da30c

test:
  secret_key_base: a8f34346ba3d720b0fc21b9befd8f2af16e6476da271457619ce501a7069e4ed0dd721cbcbeda96e6c931076790ca70921947d8c40f80bb812eebc8c188f4872

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
